name: Sync OpenAPI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  update-from-source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fern-api/sync-openapi@v2
        with:
          branch: main
          auto_merge: false
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: IcePanel/ice-dev-docs
          update_from_source: true
